Pages/Contacts/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ContactManager.Data;
using ContactManager.Models;
using ContactManager.Pages.Contacts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using ContactManager.Authorization;

namespace ContactManager.PagesContacts
{
    public class DetailsModel : DI_BasePageModel
    {
        public DetailsModel(
            ApplicationDbContext context,
            IAuthorizationService authorizationService,
            UserManager<IdentityUser> userManager)
            : base(context, authorizationService, userManager)
        {
        }

        public Contact Contact { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Contact? _contact = await Context.Contact.FirstOrDefaultAsync(m => m.ContactId == id);

            if (_contact == null)
            {
                return NotFound();
            }
            Contact = _contact;

            var isAuthorized = User.IsInRole(Constants.ContactManagersRole) ||
                            User.IsInRole(Constants.ContactAdministratorsRole);

            var currentUserId = UserManager.GetUserId(User);

            if (!isAuthorized
                && currentUserId != Contact.OwnerID
                && Contact.Status != ContactStatus.Approved)
            {
                return Forbid();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int id, ContactStatus status)
        {
            var contact = await Context.Contact.FirstOrDefaultAsync(
                                                    m => m.ContactId == id);

            if (contact == null)
            {
                return NotFound();
            }

            var contactOperation = (status == ContactStatus.Approved)
                                                    ? ContactOperations.Approve
                                                    : ContactOperations.Reject;

            var isAuthorized = await AuthorizationService.AuthorizeAsync(User, contact,
                                        contactOperation);
            if (!isAuthorized.Succeeded)
            {
                return Forbid();
            }
            contact.Status = status;
            Context.Contact.Update(contact);
            await Context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Users.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ContactManager.Pages;

public class UserModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly UserManager<IdentityUser> _userManager;

    public UserModel(ILogger<IndexModel> logger, UserManager<IdentityUser> userManager)
    {
        _userManager = userManager;
        _logger = logger;
    }

        public IList<UserRolesViewModel> model { get; set; } = new List<UserRolesViewModel>();

        public class UserRolesViewModel
        {
            public string UserName { get; set; }
            public string Email { get; set; }
            public IEnumerable<string> Roles { get; set; }
        }

        public async Task<IActionResult> OnGetAsync()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            Console.WriteLine(currentUser);
            var users = await _userManager.Users.ToListAsync();
            Console.WriteLine(users);

            foreach (IdentityUser user in users)
            {
                UserRolesViewModel urv = new UserRolesViewModel()
                {
                    UserName = user.UserName,
                    Email = user.Email,
                    Roles = await _userManager.GetRolesAsync(user)
                };
                
                model.Add(urv);
            }
            return Page();
        }
}

Pages/Users/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ContactManager.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ContactManager.Pages.Users
{
    [Authorize(Roles = "ContactAdministrators")]
    public class DetailsModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;

        private readonly RoleManager<IdentityRole> _roleManager;  

        private readonly ILogger<DetailsModel> _logger;

        public string userName { get; set; }

        public string Email { get; set; }
        
        public string Id { get; set; }
        [BindProperty]
        public String NewRoleType { get; set; }
        public IEnumerable<string> roles { get; set; }
        
        public DetailsModel(ILogger<DetailsModel> logger, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;  

            _logger = logger;

        }


        public async Task<IActionResult> OnGetAsync(string id)
        {
            ViewData["roles"] = _roleManager.Roles.ToList();  

            var user = await _userManager.FindByIdAsync(id);
            roles = await _userManager.GetRolesAsync(user);
            
            Id = id;
            userName = user.UserName;


            return Page();
        }

        public async Task<IActionResult> OnPostAddRoleAsync(string Id)
        {
            if(NewRoleType == null) {
                return RedirectToPage("./Index");

            } else {
                var user = await _userManager.FindByIdAsync(Id);
                var userRoles = await _userManager.GetRolesAsync(user);
                await _userManager.RemoveFromRolesAsync(user, userRoles.ToArray());

                await _userManager.AddToRoleAsync(user, NewRoleType);

                return RedirectToPage("./Index");
            }

        }

        public async Task<IActionResult> OnPostRemoveRoleAsync(string Id)
        {
            var user = await _userManager.FindByIdAsync(Id);
            var userRoles = await _userManager.GetRolesAsync(user);
            await _userManager.RemoveFromRolesAsync(user, userRoles.ToArray());

            return RedirectToPage("./Index");
        }


    }
}

Pages/Users/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ContactManager.Pages.Users;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly UserManager<IdentityUser> _userManager;

    public IndexModel(ILogger<IndexModel> logger, UserManager<IdentityUser> userManager)
    {
        _userManager = userManager;
        _logger = logger;
    }

        public IList<UserRolesViewModel> userList { get; set; } = new List<UserRolesViewModel>();

        public class UserRolesViewModel
        {
            public string UserName { get; set; }
            public string Id { get; set; }

            public string Email { get; set; }
            public IEnumerable<string> Roles { get; set; }
        }

        public async Task<IActionResult> OnGetAsync()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            Console.WriteLine(currentUser);
            var users = await _userManager.Users.ToListAsync();
            Console.WriteLine(users);

            foreach (IdentityUser user in users)
            {
                Console.WriteLine(user.Id);
                UserRolesViewModel urv = new UserRolesViewModel()
                {
                    UserName = user.UserName,
                    Id = user.Id,
                    Email = user.Email,
                    Roles = await _userManager.GetRolesAsync(user)
                };

                userList.Add(urv);
            }
            return Page();
        }
}

Pages/Users/Details.cshtml
@page
@model ContactManager.Pages.Users.DetailsModel
@{
    ViewData["Title"] = "User Details";
    var AllRoles = (List<IdentityRole>)ViewData["roles"]; 

}

<h1>@ViewData["Title"]</h1>

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.userName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.userName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.roles)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.roles)
        </dd>
        <dd class="col-sm-10">

    <form method="post">
        <table>

            <tr>
                <td></td>
                <input type="hidden" name="Id" value="@Html.DisplayFor(model => model.Id)"> 
                <select name="NewRoleType">
                    <option value="">Select a role</option>
                    <option value="ContactManagers">ContactManagers</option>
                    <option value="ContactAdministrators">ContactAdministrators</option>
                </select>
                <td><input type="submit" value="Add to role" asp-page-handler="AddRole" class="btn btn-primary"/></td>
            </tr>
        </table>
        <hr/>
    </form>
        <form method="post">
        <table>

            <tr>
                <td></td>
                <input type="hidden" name="Id" value="@Html.DisplayFor(model => model.Id)"> 
                <td><input type="submit" value="Remove from role" asp-page-handler="RemoveRole" class="btn btn-danger"/></td>
            </tr>
        </table>
        <hr/>
    </form>

        @foreach (var item in AllRoles) {
            <div>@item</div>
        }
        </dd>
    </dl>
</div>

Pages/Users/Index.cshtml
@page
@model ContactManager.Pages.Users.IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div>

    <table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => Model.userList[0].UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => Model.userList[0].Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => Model.userList[0].Roles)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.userList) {
            <tr>
                <td>
                    @item.UserName
                </td>
                <td>
                    @item.Email
                </td>
                <td>
                    @if(item.Roles.Count() > 0){
                        @foreach (var role in item.Roles)
                        {                        
                            @role

                        }
                    } else {
                        <div>n/a</div>
                    }
                </td>
                <td>
                    <a asp-page="./Details" asp-route-id="@item.Id">Details</a>

                </td>
            </tr>
            }
        </tbody>
    </table>
</div>